### ISSUE TITLE
アーティスト名から曲リストに遷移

### ISSUE THREAD

**Issue by koiking213** [co-akuma-voice/karaoke_note#10]

**Comment by koiking213** [comment]
@co-akuma-voice こんな感じでどうでしょう
![タイトルなし](https://github.com/co-akuma-voice/karaoke_note/assets/26344857/e2d3769d-6689-46f5-b9d1-6dbc74e01f86)

**Comment by co-akuma-voice** [comment]
ここからさらに曲名をタップすると展開する or 曲ページに遷移するならいいと思います。
