### ISSUE TITLE
Plans 登録後に本登録した曲の Latest ページにおける表示順序について、Plans 登録のタイミングが基準となる

### ISSUE THREAD

**Issue by co-akuma-voice** [co-akuma-voice/karaoke_note#121]
バグってほどではない。
事前に Plans に曲を入れたい状態でそれを歌うと、その日の最初に歌った扱いされる。
本登録（スコアを登録したとき）のタイミングの方が自然ではないだろうか。

**Comment by co-akuma-voice** [comment]
バグってほどではない。

**Comment by koiking213** [comment]
これ難しいな、裏で時刻も取る(当日以外は0時扱いにする)とか？

**Comment by koiking213** [comment]
もしくは本登録時にIDを振りなおすか

**Comment by co-akuma-voice** [comment]
> もしくは本登録時にIDを振りなおすか

これが無難な気がします。0 を再指定すると自動で振ってくれるっぽい？
最大値は DB が持っていて、それに +1 する形。
