### ISSUE TITLE
補完候補が邪魔になる

### ISSUE THREAD

**Issue by koiking213** [co-akuma-voice/karaoke_note#173]
![Screenshot_20241009-174922.png](https://github.com/user-attachments/assets/e55b3342-a14f-45b4-a39d-58373ddc90d2)

**Comment by co-akuma-voice** [comment]
対応案としてはどちらかでしょうか？
(1) 表示する候補の上限数を設定し、それ以上は ... とかで表示しないようにする
(2) 検索ヒット数が閾値以上であれば「検索結果が多すぎる」旨を表示してさらなる絞り込みを促す

**Comment by koiking213** [comment]
候補をスクロール可能にするとかもありえるかな
他のアプリがどんな仕様にしてるかちょっと見てみます

**Comment by koiking213** [comment]
YouTube Musicなんかは上限が4件に設定されてる
それぐらいで良い気もするので少なめの上限でちょっとやってみます
