### ISSUE TITLE
補完機能が欲しい

### ISSUE THREAD

**Issue by co-akuma-voice** [co-akuma-voice/karaoke_note#29]

**Comment by koiking213** [comment]
アーティストのページとか曲のページから追加するからいいかーと思ってたけどPlansができたことによりにわかに需要が高まっている

**Comment by koiking213** [comment]
アーティスト名は補完したいとして、曲名はどうしよう？
新曲を登録する機会の方が多いと考えると邪魔になるだけな気もする

**Comment by koiking213** [comment]
まあ補完機能を使ってみてから考えればいいか
