### ISSUE TITLE
採点方式ごとに点数を分けて管理

### ISSUE THREAD

**Issue by koiking213** [co-akuma-voice/karaoke_note#33]
その日は基本的に同じものを使うと思われるので、曲ごとに持たせるよりはどこかに切り替えボタンを用意する

**Comment by co-akuma-voice** [comment]
Segmented button 的な見た目がいいかなと思いますね。
<https://m3.material.io/components/segmented-buttons/overview>

**Comment by koiking213** [comment]
保存時はドロップダウンメニューにして、前回の情報を覚えておくのが良さそう
