### ISSUE TITLE
画面幅が狭い端末では日付表示が2段になる。

### ISSUE THREAD

**Issue by co-akuma-voice** [co-akuma-voice/karaoke_note#43]
スコア一覧画面における症状。

**Comment by co-akuma-voice** [comment]
デザインの改善で対応できると思う。

**Comment by koiking213** [comment]
https://github.com/co-akuma-voice/karaoke_note/tree/improve-table-appearance ブランチでどうなるか確認してみてほしいです。

**Comment by co-akuma-voice** [comment]
YYYY/MM/DD が YY/MM/DD 表記になりました。幅が狭くなったので1段で表示できるようになりました。
