### ISSUE TITLE
一部アーティストを開こうとするとアプリが落ちるので調査する

### ISSUE THREAD

**Issue by co-akuma-voice** [co-akuma-voice/karaoke_note#57]
Fiction Junction WAKANA/KEIKO

**Comment by koiking213** [comment]
スラッシュが怪しい。。
navControlのrouteが以下みたいな感じになっているので。
https://github.com/co-akuma-voice/karaoke_note/blob/ebb21c8806eaffb575166e59905fce9e98d8022b/app/src/main/java/com/example/karaoke_note/MainActivity.kt#L76

**Comment by koiking213** [comment]
ちょうど[別の問題](https://github.com/co-akuma-voice/karaoke_note/issues/55#issuecomment-1823152894)で困っていたので、原因がスラッシュなら引き取ります。

**Comment by co-akuma-voice** [comment]
検証してないけど、スラッシュが原因だとは思います。FictionJunction KAORI などは無問題なので。

**Comment by co-akuma-voice** [comment]
再現しなくなってました。
