### ISSUE TITLE
採点方式でフィルタリング表示する機能

### ISSUE THREAD

**Issue by co-akuma-voice** [co-akuma-voice/karaoke_note#71]
![path16-4-0-5](https://github.com/co-akuma-voice/karaoke_note/assets/137681371/a4ef6bd3-8a1a-4c8f-9ae2-6d59c24c8c18)
こんな感じ？

**Comment by koiking213** [comment]
これ、現状AppBarにあるけどどこまでを適用範囲としよう。
LatestとList (のAll songs) には適用されてPlansには適用されないとか？

**Comment by co-akuma-voice** [comment]
それでいいとおもいます

**Comment by koiking213** [comment]
JOYかDAMかの2択より、個別にもグループでも選択できるほうが良さげ
クソ雑な画像失礼いたします
![image](https://github.com/user-attachments/assets/2227df25-deac-4516-b472-d346232fcac8)

**Comment by co-akuma-voice** [comment]
これは例えば JOY なら全国採点□とか分析採点AI□とかってことですよね？確かにそうですね

**Comment by koiking213** [comment]
デフォルト状態かどうかによるアイコンの変更、こんな感じでどうでしょう？

![image](https://github.com/user-attachments/assets/e0714859-2165-4aec-a795-39f82ea8e597)
![image](https://github.com/user-attachments/assets/28ddb8f8-1f84-4f42-82b4-17290f0acd2a)

**Comment by co-akuma-voice** [comment]
Nice !!

**Comment by co-akuma-voice** [comment]
フィルターを適用すると Latest ページの Recompose ができてないっぽい

**Comment by co-akuma-voice** [comment]
こんな感じ？
![ビットマップ](https://github.com/user-attachments/assets/3803081a-0c97-4b3e-b984-0529cabbfca4)

**Comment by koiking213** [comment]
良さそう！

**Comment by koiking213** [comment]
> フィルターを適用すると Latest ページの Recompose ができてないっぽい

「リストの最後の要素にアクセスしたら次を読み込む」をやろうとして、フィルタリング前のリストのサイズを見てたから追加ロードができてなかった。
それは直せば良いけど、対象のスコアが0件のときに追加ロードできないから別の条件を考えいないといけない。。
