### ISSUE TITLE
検索機能の追加

### ISSUE THREAD

**Issue by koiking213** [co-akuma-voice/karaoke_note#8]
- [ ] 曲検索
- [ ] アーティスト検索
~~点数による絞り込み~~

**Comment by co-akuma-voice** [comment]
検索窓の場所は TopBar の「カラオケ点数管理」と書いてある場所がいいのではと思います。

**Comment by koiking213** [comment]
点数による絞り込みはフィルタのほうがふさわしそうなので一旦外します

**Comment by koiking213** [comment]
虫眼鏡を押すと検索画面に遷移するタイプと、検索窓が常駐しているタイプがいる
このアプリだと検索したい画面が多いから常駐タイプが良さそう

**Comment by koiking213** [comment]
遷移タイプのイメージ:
![image](https://github.com/user-attachments/assets/a55a56be-d01f-4e9a-93c2-1902c12aa0aa)

常駐タイプのイメージ:
![image](https://github.com/user-attachments/assets/df73a860-9939-429e-bb5e-4d78611fb9e3)
